### PR TITLE
swagger-ui 3 version updated to 3.23.1

### PR DESCRIPTION
**Pull request by patrickkwang**
I needed swagger-ui's new (3.23.0) support for example objects in `requestBody`.

### CODE REVIEW

**Comment by patrickkwang** [comment]
Just found this bit of documentation:
https://github.com/rochacbruno/flasgger#externally-loading-swagger-ui-and-jquery-jscss

So my particular problem is solvable without updating the internal swagger-ui. Still it's probably not a bad idea to periodically update the included version, so I'll leave the PR open.

**Comment by billyrrr** [comment]
Note: previous version of ```swagger-ui``` is ```3.20.5``` (#267 )

**Comment by ckdanny** [comment]
@patrickkwang 
May I know your implementation?
I have tried following code but still cannot use `examples`
```python
app = Flask(__name__, static_folder=os.path.abspath('../static'))

# swagger_config = Swagger.DEFAULT_CONFIG
# swagger_config['swagger_ui_bundle_js'] = '/static/js/swagger-ui-bundle.js'
# swagger_config['swagger_ui_standalone_preset_js'] = '/static/js/swagger-ui-standalone-preset.js'
# swagger_config['swagger_ui_css'] = '/static/css/swagger-ui.css'
swagger = Swagger(app, config= swagger_config)
```

```yaml
- name: processedData
  in: body
  required: true
  description: processed data from data mart
  schema:
    type: object
#    examples:
#      zero:
#        value: '0'
#        summary: A sample limit value
#      max:
#        value: '50'
#        summary: A sample limit valu
```

**Comment by patrickkwang** [comment]
Your use of `in: body` suggests you're using OpenAPI 2.0, which does not appear to support multiple `examples`. The schema object does support a single [`example`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#model-with-example).

With OpenAPI 3.0 you could provide `examples`, but it should go one level up, as a sibling of `schema` instead of a child.

**Comment by ckdanny** [comment]
@patrickkwang 
Thanks! I haved solved it.

**Pull request merged**
